### ISSUE TITLE
Table XY doesn't exist

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/Module-Tickets#5]
I just opened Administration/Ticket Settings and I got this error message over the header where it says Ticket Settings:

> Table '1_ogp.ogp_ticket_settings' doesn't exist

"1_ogp" is the name of my OGP database

**Comment by Zorrototo** [comment]
I just reinstalled it, and I don't have this error. I didn't have this error on older installs either, even when the new DB structure was added.

If you go to Admin,Modules, UPDATE MODULES does it work then?

**Comment by Adjokip** [comment]
I do not get that message either.

The table restructure which happened at the same time when adding attachments may be the fault, but I doubt that.

If Omano's suggestion doesn't work, try a clean install of the module ... or if you cannot do a clean install, create the table by looking at the query [here](https://github.com/OpenGamePanel/Module-Tickets/blob/master/modules/tickets/module.php#L91) - you'll then need to add the default settings in the _Ticket Settings_ page.

**Comment by rocco27** [comment]
Sorry for late, I reinstalled the module from the scratch and no more error. :)
